### ISSUE TITLE
integrate pandas

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/HPO#2]
I'm always encountering troubles to handle data. Probably I need to use pandas, seems to be a cool tool to load, manipulate data. and I have a sense the data structure as weil as manipulation is similar to R....

http://pandas.pydata.org

**Comment by WeiFoo** [comment]
Done

**Comment by timm** [comment]
did pandas fix your problems?

**Comment by WeiFoo** [comment]
pandas is kind of a data structure, which makes it easier to manipulate data.
