### ISSUE TITLE
mini step to show hyper parameters optimization on delay 

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/HPO#3]
The data in apache has four labels: nondelay, low delay, medium delay, high delay. 

I temporarily convert data into binary classes, only nondelay and delay.

if it works and we can do multiple classes.

**Comment by WeiFoo** [comment]
## EXP1: np = 10
- **np = 10**, DE, life = 5, 
- **repeat 5 times for each learner and each goal**, each time generate different training and tuning data 
- learner: CART_classifier, RF_classifier
- class labels:  delay and nondelay( all "low delay", "medium delay","high delay" are converted into "delay")

## Result:
- [tune precision](https://github.com/ai-se/HPO/issues/5) 
- [tune f](https://github.com/ai-se/HPO/issues/6)

## Observation:
- the goal slightly improved
- also the other goals are not changed a lot...

**Comment by WeiFoo** [comment]
## EXP2: np = 60
- **np = 60**, DE, life = 5, 
- **repeat 5 times for each learner and each goal**, each time generate different training and tuning data 
- learner: CART_classifier, RF_classifier
- class labels:  delay and nondelay( all "low delay", "medium delay","high delay" are converted into "delay")

## Result:
- [tune precision](https://github.com/ai-se/HPO/issues/7) 
- [tune f](https://github.com/ai-se/HPO/issues/8)

## Observation:
- the same....as EXP 1

**Comment by timm** [comment]
try GALE? dunno
